"""premièrement je devrais ajouter les deux for dans mon programe.Je vais essayer de créer une for"""
"""Je vai essyer de créer une espèce de fonction pour faire divese tâche dans mon programe comme google"""
"""Je vais créer un boucle à ligne 39 ou j'avais marquée error plus qu'une fois"""
"""je vais rajouter un site de paril pour de s course de kiwi"""
"il faut que je rajoute plus de documentati0n dans mon code"